import { GridColDef } from '@mui/x-data-grid';
import NftCell from './pages/components/nft-cell';

export const columns: GridColDef[] = [
  {
    field: 'pfp',
    headerName: 'PFP',
    width: 70,
    renderCell: NftCell,
    sortable: false,
    resizable: false,
    disableColumnMenu: true,
    disableReorder: true,
  },
  {
    field: 'col1',
    headerName: 'Handle',
    width: 160,
    sortable: false,
    resizable: false,
    disableColumnMenu: true,
    disableReorder: true,
  },
  {
    field: 'col2',
    headerName: 'Address',
    width: 400,
    sortable: false,
    resizable: false,
    disableColumnMenu: true,
    disableReorder: true,
  },
  {
    field: 'col3',
    headerName: 'Name',
    width: 150,
    sortable: false,
    resizable: false,
    disableColumnMenu: true,
    disableReorder: true,
  },
  {
    field: 'col4',
    headerName: 'Following',
    width: 100,
    sortable: true,
    resizable: false,
    disableColumnMenu: true,
    disableReorder: true,
  },
  {
    field: 'col5',
    headerName: 'Followers',
    width: 100,
    sortable: true,
    resizable: false,
    disableColumnMenu: true,
    disableReorder: true,
  },
  {
    field: 'col6',
    headerName: 'Posts',
    width: 100,
    sortable: true,
    resizable: false,
    disableColumnMenu: true,
    disableReorder: true,
  },
];